dataset: coco
model:
  name: ProtoGCN
  num_classes: 5 
  num_person: 1

data:
  num_frames: 60
  num_nodes: 17
  root: data

training:
  output_root: output
  batch_size: 32
  learning_rate: 0.025
  epochs: 10 
  device: cpu
  num_workers: 4
  num_subjects: 5
  use_augmentation: true

inference:
  output_root: output
  device: cpu
  checkpoint: output/.../best*.pth
  output: output/result_inference.json
  split: test
  sample_index: 0
  num_subjects: 5 
